---

- hosts: clusterBrokerNodes:clusterBrokerAddNodes:clusterBookeeperNodes:clusterBookeeperAddNodes
  gather_facts: true
  roles:
    - java
    - common
    - install
    - configure

# - hosts: clusterBrokerNodes[0]
#   gather_facts: true
#   tasks:
#     - name: initialize apache pulsar cluster metadata
#       shell: |
#         {{ apachePulsarInstallDir }}/apache-pulsar/bin/pulsar initialize-cluster-metadata \
#           --cluster {{ apachePulsarClusterName }} \
#           --zookeeper {{ apachePulsarZookeeperAddressString }}\
#           --configuration-store {{ apachePulsarZookeeperAddressString }} \
#           --web-service-url http://{{ ansible_ssh_host }}:8080/ \
#           --broker-service-url pulsar://{{ ansible_ssh_host }}:6650/ > {{ apachePulsarLogDir }}/initialize-cluster-metadata.log
#       args:
#         creates: "{{ apachePulsarLogDir }}/initialize-cluster-metadata.log"

- hosts: clusterBrokerNodes:clusterBrokerAddNodes
  gather_facts: true
  tasks:
    - include_role:
        name: service
        tasks_from: broker
    - import_role:
        name: serviceState
      vars:
        serviceName: broker
        serviceState: started
    - include_role:
        name: portCheck
      vars:
        portNumber: "{{ item }}"
        portStatus: started
      loop:
        - "{{ apachePulsarBrokerServicePort }}"
        - "{{ apachePulsarBrokerWebServicePort }}"

- hosts: clusterBookeeperNodes:clusterBookeeperAddNodes
  gather_facts: true
  tasks:
    - include_role:
        name: service
        tasks_from: bookkeeper
    - import_role:
        name: serviceState
      vars:
        serviceName: bookkeeper
        serviceState: started
    - include_role:
        name: portCheck
      vars:
        portNumber: "{{ item }}"
        portStatus: started
      loop:
        - "{{ apachePulsarBookiePort }}"
        - "{{ apachePulsarBookieHttpServerPort }}"