---

- name: install awslogs agents
  package:
    name: awslogs
    state: latest
    update_cache: true

- name: update location for pulsar-logs in cloudwtch agent conf
  blockinfile:
      path: /etc/awslogs/awslogs.conf
      block: |
        [cloudwatch-pulsar-logs]
        time_zone = LOCAL
        datetime_format = %b %d %H:%M:%S
        file = {{ apachePulsarInstallDir }}/logs/*.log
        buffer_duration = 5000
        log_stream_name = {instance_id}
        initial_position = start_of_file
        log_group_name = cloudwatch-pulsar-logs

- name: update aws region of clouwatch agent
  lineinfile:
    path: /etc/awslogs/awscli.conf
    regexp: '^region ='
    line: "region = {{ aws_pulsar_ec2_region }}"

- name: service enable awslogsd
  service:
    name: awslogsd
    state: restarted
    enabled: true