---

- name: creating apachePulsar group
  group:
    name: "{{  apachePulsarGroup }}"
    gid: "{{ apachePulsarGroupId }}"
    state: present

- name: creating apachePulsar user
  user:
    name: "{{ apachePulsarUser }}"
    comment: apachePulsar Default User
    uid: "{{ apachePulsarUserId }}"
    group: "{{ apachePulsarGroup }}"