---

javaVersion: 8
updateJava: false # only when you need to update java version

useSystemFirewall: false

apachePulsarGroup: apachePulsar
apachePulsarUser: apachePulsar
apachePulsarGroupId: 8000
apachePulsarUserId: 8000

apachePulsarInstallDir: /elasticdata
apachePulsarDataDir: "{{ apachePulsarInstallDir }}/apachePulsar-data"
apachePulsarLogDir: "{{ apachePulsarInstallDir }}/apachePulsar-logs"

# JVM Settings
apachePulsarXms: 6G
apachePulsarXmx: "{{ apachePulsarXms }}"
apachePulsarPort: 9092
apachePulsarJmxPort: 9999
apachePulsarVmMaxMapCount: 100000

# zookeeper string should comma separate value
# 192.168.56.100:2181,192.168.56.101:2181,192.168.56.102:2181
apachePulsarZookeeperAddressString: 10.32.20.165:2181
apachePulsarZookeeperConnectionTimeoutMs: 10000

# please use name like <environment>-apachePulsar, so it get distinct name in NewRelic
apachePulsarClusterName: development-apachePulsar

apachePulsarVersion: 2.4.0
apachePulsarTarLocation: "/home/davinderpal/packages/apache-apachePulsar-{{ apachePulsarVersion }}-bin.tar.gz"

# below will be used while decommission/downgrade only
apachePulsarOldVersion: 2.3.0

### Production Optimization Parameters
### if nothing is set then it will use default values.
