---

- name: Creating symlink to latest version | {{ pulsarVersion }}
  file:
    src: "{{ pulsarInstallDir }}/apache-pulsar-{{ pulsarVersion }}"
    dest: "{{ pulsarInstallDir }}/apache-pulsar"
    owner: "{{ pulsarUser }}"
    group: "{{ pulsarGroup }}"
    state: link
  register: pulsarSymlinkStatus