---

- name: copy & unarchieve apache-pulsar
  include_tasks: download.yml

- name: Create apache-pulsar dir symlink
  include_tasks: createSymlink.yml

- name: Setting apache-pulsar version into profile.d
  include_tasks: envSet.yml